colorscheme smau
set nocompatible

" Hybrid line numbering
set number
set relativenumber
set cursorline

" Tabs
set tabstop=8

" Indentation
set autoindent
set smartindent

" Backup
set undofile
set backup
set undodir=~/.config/vim/.undo//
set backupdir=~/.config/vim/.backup//
set directory=~/.config/vim/.swp//

set viminfo+=n~/.config/vim/viminfo

" Use system-wide clipboard
set clipboard+=unnamedplus
" instead, use "* and "+ registers
" "+ to yank and paste elsewhere
" "* to paste from elsewhere

" Show hidden characters
set listchars=tab:│\ ,trail:-
set list

" Disable mouse
set mouse=

set spelllang=en
set spell
set spelloptions=camel

" Netrw config
let g:netrw_winsize=-20  " 20 cols is nominal min
let g:netrw_preview=1  " vertical splitting
let g:netrw_liststyle=0  " thin browsing
" let g:netrw_liststyle=3  " tree-style file browsing
let g:netrw_browse_split=4
" These tank performance with unnamedplus clipboard, don't use
" (<https://github.com/neovim/neovim/issues/23650#event-23261972027>)
" let g:netrw_list_hide= '\(^\|\s\s\)\zs\.\S\+'  " hide dotfiles by default
" let g:netrw_banner=0

" If `nvim` invoked with no argument, start in netrw
" augroup VimStartup
"   autocmd!
"   autocmd VimEnter * if expand("%") == "" | Vexplore | endif
" augroup END
