colorscheme smau
set nocompatible

" Hybrid line numbering
set number
set relativenumber
set cursorline

" Tabs
set tabstop=8

" Indentation
set autoindent
set smartindent

" Backup
set undofile
set backup
set undodir=~/.config/vim/.undo//
set backupdir=~/.config/vim/.backup//
set directory=~/.config/vim/.swp//

set viminfo+=n~/.config/vim/viminfo

" Show hidden characters
set listchars=tab:│\ ,trail:-
set list

" Disable mouse
set mouse=

set spelllang=en
set spell
set spelloptions=camel
